[package]
name = "wheeltimer"
version = "0.1.0"
edition = "2024"
authors = ["cyj0122 <269873721@qq.com>"]
description = "wheelTimer is Netty's HashedWheelTimer implementation based on Rust"

[dependencies]
tokio = {version = "1.43.0", features = ["full"]}

[dev-dependencies]
rand = "0.8"